### ISSUE TITLE
Get status not working?

### ISSUE THREAD

**Issue by ghost** [sentanos/roblox-js#102]
So I took the code from some other thread that was answered..

And it comes up with this error:

`await is only valid in async function`

`const status = await rbx.getStatus(await rbx.getIdFromUsername(username));`

**Comment by suufi** [comment]
Before copy & pasting anything you see on the internet, be sure you understand what it does first. Read this article to understand more about async/await: https://anidiots.guide/other-guides/async-await.

**Comment by ghost** [comment]
Still confused..

**Comment by ghost** [comment]
is rbx.getStatus not a async function?

**Comment by suufi** [comment]
Yes and that's why you must use it inside an async function while awaiting
it.

**Comment by sentanos** [comment]
The issue is not rbx.getStatus, it has nothing to do with whether rbx.getStatus is an async function. The function _using async/await_ has to be async.

**Comment by ghost** [comment]
so I have to put it in a async function.. ohhhh ok.
