### ISSUE TITLE
Group admin page load failed, make sure the user is in the group and is allowed to handle join requests

### ISSUE THREAD

**Issue by iLordOfAviation** [sentanos/roblox-js#108]
`Unhandled rejection Error: Group admin page load failed, make sure the user is in the group and is allowed to handle join requests`

I'm 100% sure my account is allowed to handle join requests, yet I'm getting this error.. Not sure if I did something to mess it up or if it's a roblox-js problem

**Comment by DamonOnYT** [comment]
Clearly, roblox is getting rid of botting. so just so you know

**Comment by DictatorMaffu** [comment]
no need to get sassy

but idk what i did, i just messed with some stuff and got it working so ig we're ok
