### ISSUE TITLE
Im attempting to use this in php, it cant find roblox-js

### ISSUE THREAD

**Issue by mwalden2004** [sentanos/roblox-js#11]
Code: 
<?php
$hi = $_GET["id"];
$rbx = require('roblox-js');
$request = require('request');
$blurb = $rbx->getBlurb($hi);
echo($blurb);
?>
Error:
Notice: Undefined index: id in /var/www/html/blurb.php on line 2
Warning: require(roblox-js): failed to open stream: No such file or directory in /var/www/html/blurb.php on line 3
Fatal error: require(): Failed opening required 'roblox-js' (include_path='.:/usr/share/php') in /var/www/html/blurb.php on line 3

**Comment by sentanos** [comment]
This is not PHP, this is node.js. It is not going to work with PHP, stop making these issues.
