### ISSUE TITLE
Making SendTrade function, roblox error.

### ISSUE THREAD

**Issue by SparkleOff** [sentanos/roblox-js#13]
I fixed that error before i posted about but totally getting a new one, the response from roblox. I was hoping you can help me out.

This is just testing so i used the encoded version that roblox does when you tamper the post. So this is my actual sendtrade function

http://pastebin.com/bkTZcQW2

and this is the string "array" i am executing with:

http://pastebin.com/wSxHsMMd

I am pretty sure i did everything right as for this test version but roblox returns that there was an error processing the request.

**Comment by sentanos** [comment]
I can't answer this because I do not have access to an account which has the ability to trade.

**Comment by sentanos** [comment]
Unless I can get more information my only guess would be making the array an actual array in the form as opposed to a string.

**Comment by SparkleOff** [comment]
Well hopefully this information can be helpful

https://gyazo.com/071b08d49bc5b89e0854f63b88568471
https://gyazo.com/99384f6ef86481e40dfb3b40926a751f
https://gyazo.com/3f54caeeb420a26b5a4590e19359abad

**Comment by SparkleOff** [comment]
It could because jar is undefined? but then i have no idea why the cookies aren't posting with the data, i have no idea where the cookies are handled.

**Comment by SparkleOff** [comment]
updated it where jar is defined and submitted the cookies, this is my function and STILL doesn't work.

https://github.com/SparkleOff/roblox-js/blob/master/lib/sendTrade.js

**Comment by sentanos** [comment]
Jar being undefined is correct, when it is passed into the http function it is automatically replaced with the global cookie jar.

**Comment by sentanos** [comment]
It is most likely related to some weird ROBLOX configuration you have to meet, I would like to investigate this for you but I simply do not have a BC account. This is not a real issue with the project and does not belong here. If you want to talk to me personally my skype and discord are on my profile.
