### ISSUE TITLE
rbx.getPlayers(...).then is not a function?

### ISSUE THREAD

**Issue by ytomasch** [sentanos/roblox-js#19]
Output: 
> Getting players
> Unhandled rejection TypeError: rbx.getPlayers(...).then is not a function
>     at C:\Users\Michael\Documents\RobloxNode\nodejs\exile.js:13:4
>     at tryCatcher (C:\Users\Michael\Documents\RobloxNode\nodejs\node_modules\blu
> ebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (C:\Users\Michael\Documents\RobloxNode\
> nodejs\node_modules\bluebird\js\release\promise.js:512:31)
>     at Promise._settlePromise (C:\Users\Michael\Documents\RobloxNode\nodejs\node
> _modules\bluebird\js\release\promise.js:569:18)
>     at Promise._settlePromise0 (C:\Users\Michael\Documents\RobloxNode\nodejs\nod
> e_modules\bluebird\js\release\promise.js:614:10)
>     at Promise._settlePromises (C:\Users\Michael\Documents\RobloxNode\nodejs\nod
> e_modules\bluebird\js\release\promise.js:693:18)
>     at Async._drainQueue (C:\Users\Michael\Documents\RobloxNode\nodejs\node_modu
> les\bluebird\js\release\async.js:133:16)
>     at Async._drainQueues (C:\Users\Michael\Documents\RobloxNode\nodejs\node_mod
> ules\bluebird\js\release\async.js:143:10)
>     at Immediate.Async.drainQueues (C:\Users\Michael\Documents\RobloxNode\nodejs
> \node_modules\bluebird\js\release\async.js:17:14)
>     at runCallback (timers.js:651:20)
>     at tryOnImmediate (timers.js:624:5)
>     at processImmediate [as _immediateCallback] (timers.js:596:5)
>

**Comment by sentanos** [comment]
It looks like you're using the wrong version of the module. The files in the examples folder only work with version 3 and up.

**Comment by ytomasch** [comment]
Looks like manually installing v3.0.3 fixed the problem as you stated, thanks. 
Strange that npm selected v2.X.X? Anyways, closing the issue.

**Comment by sentanos** [comment]
Sorry about that, I had to patch v2 and didn't realize that it was automatically set to latest. I've fixed it and installs should use v3.0.3 now.
