### ISSUE TITLE
Roblox - GetPlayers function

### ISSUE THREAD

**Issue by ConfidentCoding1** [sentanos/roblox-js#21]
![screenshot_1686](https://cloud.githubusercontent.com/assets/11546642/25003066/852fe634-2045-11e7-8057-a5fe9568c94d.png)

I am trying to call the GetPlayers function from Roblox Studio.

However every time I call the function the returned table always as 0 entries/arrays in it.

**Comment by sentanos** [comment]
First of all the players are contained in the `data.players` field of the table. Second, even if you tried to get the length of this it would not work because it is a dictionary and you cannot get the length of those using `#`. Here is what you would do to get the number of players returned:

```lua
local function count (t)
  local sum = 0
  for i in next, t do
    sum = sum + 1
  end
  return sum
end

local players = api.getPlayers(6, 4, false).data.players
print(count(players))
```

**Comment by ConfidentCoding1** [comment]
Thank You!
