### ISSUE TITLE
getPlayers returning many duplicates

### ISSUE THREAD

**Issue by andrewstephenson-v1** [sentanos/roblox-js#22]
Hi, firstly thank you for this really useful library.

I've been using it successfully for a while now but I think the group that I'm monitoring has become too large.

We have over 2,500 members and recently getPlayers started to return nearly 8,000 players. In this case there are only 420 unique users and each is duplicated 19 times.

The groupID is 3146600.

Is this a known issue?

many thanks

**Comment by sentanos** [comment]
This is due to a bug caused by a recent ROBLOX change. I patched this yesterday in cb96147 but forgot to publish it to npm. I've done it now and you should be able to use `npm install` to update the module to the latest version 3.0.6 which should fix the issue.

**Comment by sentanos** [comment]
This problem is reflected in v2 as well and in order to maintain compatibility with roblox-js-server that has also been patched in v2.3.7, if you happen to be using it you can update the dependencies with the second set of instructions [here](https://github.com/sentanos/roblox-js-server#updating).

**Comment by andrewstephenson-v1** [comment]
Thanks for the fix, confirmed working.
