### ISSUE TITLE
example: purchase ad 

### ISSUE THREAD

**Issue by TheSneak** [sentanos/roblox-js#23]
Can you provide an example demonstrating how to use this library to purchase an ad, please? I can't find that specific functionality in the wiki nor in the code.
Thanks

**Comment by mwalden2004** [comment]
Umm, If you want that your going to have to do it your self,

**Comment by sentanos** [comment]
This library doesn't support every site action under the sun, only main site functions that people would likely need. Purchasing an ad is pretty obscure, it is not supported and I will likely not add it.

If you want to make it yourself you can of course use the existing functions as a base which should make it much easier.
