### ISSUE TITLE
"Message failed, make sure you are logged in"

### ISSUE THREAD

**Issue by Vritix** [sentanos/roblox-js#30]
#This error keeps popping up every time I try to send a message, and yes I am logged in. I've made sure I was logged in by making the function wait until I was sure the bot was logged in and logging to the console, but it's still giving me this error. 

Any help?

**Comment by sentanos** [comment]
Please put the following in the _exact same place_ you are sending the message:
```javascript
rbx.getCurrentUser().then(console.log);
```
To make absolutely certain you are logged in and _using the correct jar file_.

**Comment by Vritix** [comment]
Yep it's logged in. It's prints the correct information.

I added you on skype + discord so we can talk easier.

**Comment by sentanos** [comment]
Alright replace your message.js file with [this](https://gist.github.com/sentanos/8294eef176fbc482e8e7f0461bd460e2) and run message again. Tell me what it outputs.

**Comment by Vritix** [comment]
`{ success: false, shortMessage: null, message: 'Captcha' }`
Also same, error :
_Message failed, make sure your are logged in._

**Comment by sentanos** [comment]
Yeah it looks like ROBLOX is requiring you to do a captcha challenge. I will say it was an issue that the correct error wasn't being thrown (it should tell you that captcha is the problem), but other than that there is no way to circumvent captcha restrictions and it cannot be a problem with ROBLOX.

This is related to [#31](https://github.com/sentanos/roblox-js-server/issues/31) on roblox-js-server, it seems like ROBLOX is enforcing captcha for messages now, though it may be limited to accounts made after a certain date (as they did with the forums), or possibly from accounts that have been detected to be sending a lot of messages.

**Comment by sentanos** [comment]
I will close this once I fix the error issue.

**Comment by Vritix** [comment]
Alright, thanks for the information.

**Comment by Vritix** [comment]
**SOLUTION:**

After some testing different accounts I realized the main issue was that my account was too new. After realizing this I logged into an account I made in 2014 and it worked **perfectly** after that. 

Hope this helps anyone! :)
