### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BottyRBLX** [sentanos/roblox-js#32]
I got this error: 
![image](https://user-images.githubusercontent.com/24595716/27003570-903fbcd4-4df9-11e7-8441-2effbcb1a2d1.png)

When running this: 
![image](https://user-images.githubusercontent.com/24595716/27003575-aebd200c-4df9-11e7-85b9-5bfe82b92307.png)

**Comment by sentanos** [comment]
You are using promises incorrectly. Remember that you have to put all following commands in a .then function.
```javascript
rbx.login('username', 'password'); // Put this at the top of the script for running during initialization, since it only needs to be done once. You don't have to use a .then here because we can assume that by the time someone sends a command the login has already completed.

rbx.getIdFromUsername(args[0])
.then(function (user) {
  var options = {
    group: 3030452,
    target: user,
    name: '[8] Headmaster'
  }
  rbx.setRank(options)
  .then(function (newRole) {
    message.channel.send('The new role is: ' + JSON.stringify(newRole));
  });
});

**Comment by BottyRBLX** [comment]
Hi, I followed your advice it worked for the most part but then this happened.

![image](https://user-images.githubusercontent.com/24595716/27195091-9cc7a2b8-5205-11e7-855d-61aa820a9a7b.png)

**Comment by BottyRBLX** [comment]
It returns undefined.

**Comment by BottyRBLX** [comment]
@sentanos

**Comment by sentanos** [comment]
You are running getShout before the login has time to complete. Something like this would ensure that you are executing the next step once the previous one has completed:

```javascript
rbx.login('username', 'password')
.then(function () {
  rbx.getShout(3030452).then(console.log);
});
