### ISSUE TITLE
It sais that roblox.js doenst exists when i installed it

### ISSUE THREAD

**Issue by DutchDevelop** [sentanos/roblox-js#35]

**Comment by ICostaEx** [comment]
Can you post the error you are getting please

**Comment by DutchDevelop** [comment]
http://prntscr.com/fmnjdv here's a screenshot

**Comment by Vritix** [comment]
It's suppose to be _roblox-js_

`const roblox = require('roblox-js')` (for JS, if you using that)

I believe you are searching for _roblox.js_, which is incorrect.
