### ISSUE TITLE
Top Bar Support?

### ISSUE THREAD

**Issue by Conmmander** [sentanos/roblox-js#37]
I've searched around and didn't seem to find any support to get whatever is inside the top status bar that is on players profile. Does this actually exist with roblox-js or do we have to make this ourselves?

**Comment by sentanos** [comment]
Getting a user's status message does not exist right now but is very easy to add - I will most likely put it in the next release.

**Comment by Conmmander** [comment]
Awesome! Thank you, I appreciate it.

**Comment by Conmmander** [comment]
I got code for this!

// Includes
var http = require('./http.js').func;
var parser = require('cheerio');

// Args
exports.required = ['userId'];

// Define
exports.func = function (args) {
    return new Promise(function (resolve, reject) {
            http({ url: 'https://www.roblox.com/users/' + args.userId + '/profile' })
            .then(function (body) {
                var matches = body.match(/data-statustext="?(.*?)"? data-edit/);
                resolve((matches && matches[1]) ? matches[1] : false);
            })
    })
}
