### ISSUE TITLE
Join Request Handling Functions return permissions error

### ISSUE THREAD

**Issue by unix-system** [sentanos/roblox-js#43]
Exact error:
`Error: Invalid permissions, make sure the user is in the group and is allowed to handle join requests
    at path\node_modules\roblox-js\lib\util\handleJoinRequestId.js:29:13
    at tryCatcher (path\node_modules\bluebird\js\release\util.js:16:23)`

I know for a fact that sending PMs, promotion, and all other functions I have tried so far relating to groups and the account (which is ranked in the target group with join request roles, as I am able to get pending join requests) has no permissions error.

Perhaps an API change?

**Comment by sentanos** [comment]
I just tested this right before and it is definitely working fine. Please show how you exactly you are using the function.

**Comment by unix-system** [comment]
`  rbx.handleJoinRequest(1180892,username,true).then(function(promiseData) {
	// Sort of secret code occurring here.
  }).catch(function(err) {
    console.error(err.stack);
  });`

That is my exact code. Again, the account is logged in properly and has full permissions.

**Comment by sentanos** [comment]
I simply cannot replicate the error. Please contact me on discord to continue this discussion: Froast#5132

**Comment by sentanos** [comment]
Please confirm whether or not version 4.0.1 fixes this.
