### ISSUE TITLE
Is your example broken?

### ISSUE THREAD

**Issue by checkraisefold** [sentanos/roblox-js#49]
```
    at Async._drainQueues (C:\Users\Dev\Desktop\misc\exileAllFromRank\node_modul
es\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Dev\Desktop\misc\exileAllFromRank\n
ode_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

The errors come crashing down.
https://pastebin.com/4iu0znNY
Says time: 0.624 MS and then doesn't do anything to group.

**Comment by checkraisefold** [comment]
ficxed, was something really stupid

**Comment by checkraisefold** [comment]
Thought I fixed it, now it says time: 0.624 MS and doesn't even do anything to group.

**Comment by sentanos** [comment]
Are you trying to exile everyone in that rank? If so pages should be null, right now you are only exiling people from exactly page 142

**Comment by checkraisefold** [comment]
I see. If I set pages to null, I get the horror of errors that are listed. It spams this error over and over. @sentanos

**Comment by checkraisefold** [comment]
This eventually happens, but no change to group members.
```
Ran out of tries for 1400
Ran out of tries for 1406
Ran out of tries for 1409
Ran out of tries for 1405
Ran out of tries for 1403
Ran out of tries for 1413
Ran out of tries for 1401
Ran out of tries for 1408
Ran out of tries for 1402
Ran out of tries for 1412
Ran out of tries for 1411
Ran out of tries for 1410
Ran out of tries for 1404
Ran out of tries for 1407
Ran out of tries for 1414
Time: : 449509.918ms
```

**Comment by sentanos** [comment]
This is because you are retrieving a lot of pages and your network or machine can't handle the large number of requests at once. You can remedy this by lowering the `maxThreads` value in the `settings.json` file.

**Comment by checkraisefold** [comment]
Or I can put it on heroku.

**Comment by checkraisefold** [comment]
Fixed, lowered maxthreads to 10. If you do not want to do that, put it on heroku.

**Comment by checkraisefold** [comment]
To fix this issue, deploy your app on Heroku or do what @sentanos said to do.

**Comment by checkraisefold** [comment]
Probably going to have to put it on heroku. 1 thread and it still does it.

**Comment by sentanos** [comment]
It could be due to something else. Are there any other errors at all other than "Ran out of tries"?
