### ISSUE TITLE
Everything was well until 'App not compatible with buildpack'

### ISSUE THREAD

**Issue by uJordy** [sentanos/roblox-js#50]
-----> App not compatible with buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

I've added node js as a buildpack for the server but it still won't work.

**Comment by uJordy** [comment]
http://prntscr.com/ghuin6 -- Screenshot of my buildpacks

**Comment by sentanos** [comment]
This project is not a buildpack. You are misunderstanding how to set it up.
