### ISSUE TITLE
Docs relating to streams

### ISSUE THREAD

**Issue by Neztore** [sentanos/roblox-js#51]
The documentation relating to involving writable streams is poor. There are no examples of how to set this up, and it appears that each 'chunk' is not the complete JSON despite what some of the documentation says.

**Comment by sentanos** [comment]
Creating and using streams is not relevant to this project and its official documentation can be found within node's actual documentation [here](https://nodejs.org/api/stream.html) though you will likely not need to access the stream directly. I'm not sure what's unclear about what is pushed to them. It says "Each player is individually written to the stream" and that's exactly what happens. Every player object in the group regardless of page will be sent. There are examples of using it with a writable stream in [savePlayers](https://github.com/sentanos/roblox-js/blob/master/examples/savePlayers.js) and other files.
