### ISSUE TITLE
Shout - Not working?

### ISSUE THREAD

**Issue by nishi7409** [sentanos/roblox-js#64]
My code - 
```js  
if (message.content.startsWith(prefix + "shout")){
    rbx.login(options)
    rbx.shout(3464814, "Testing...  Please work!!")
  }

Error - http://prntscr.com/h3i88v

**Comment by sentanos** [comment]
You are failing to use promises to wait for the login to complete.
```javascript
rbx.login(options)
.then(function () {
  rbx.shout(...);
});
```
Also, it looks like you are making a discord bot. Instead of logging in when the command is executed just login when the bot is turned on and all the commands should be executed from that user.
```javascript
// Put this at the top
rbx.login(options);
```

**Comment by nishi7409** [comment]
Ah, fixed (forgot to comment earlier)!
