### ISSUE TITLE
Permissions failing?

### ISSUE THREAD

**Issue by kinkocat** [sentanos/roblox-js#7]
The rbx user logged in has full group permissions to set ranks, shout etc. The target user is in the group as well. However i keep getting this persistent error within the command prompt upon running one of the functions. https://gyazo.com/82ad309adca128a27389cbf9d02f49b5 This all worked for me the first time i set it up, however it is not working now. Perhaps ROBLOX changed something on their API?

**Comment by sentanos** [comment]
There was an API change very recently that broke login (and therefore everything that depends on a logged in user) and it was fixed in a new version. Please confirm that your roblox-js version is the latest 2.2.1 and if it is not run "npm update" to get it.

**Comment by kinkocat** [comment]
I just end up getting this error when i run a command that is suppose to post a message in the group, https://gyazo.com/c983cce576ef77cdd6e80831aef45ed1 again the account is logging in just fine, and it has the correct permissions to able to shout in the group.

**Comment by sentanos** [comment]
I am unable to replicate the problem, please show me the exact code you are using so I can confirm that it's being used correctly.

**Comment by kinkocat** [comment]
a "-" just represents classified strings, example, password, token etc.

```javascript
const Discord = require('discord.js');
const bot = new Discord.Client();
const rbx = require('roblox-js');
const jar = {'session': '-'};
const token = '-';
const Prefix = "!";


// INITIALIZING



bot.on("ready", () => {
    console.log(`Ready to server in ${bot.channels.size} channels on ${bot.guilds.size} servers, for a total of ${bot.users.size} users.`);
    
});

rbx.login('-', '-')
.then(function (info) {
    console.log('Logged in with ID ' + info.userId)
})

.catch(function (err) {
    console.error(err.stack);
});


// ACTION EVENTS



bot.on("guildMemberAdd", member => {
     member.guild.defaultChannel.sendMessage("Welcome **" + member.user.username + "** to NYPD Official, " + "<@" + member.user.id + ">");
});


bot.on("guildBanAdd", (guild,user) => {
    guild.defaultChannel.sendMessage("The Ban Hammer has been dropped on **" + user.username + "** REKT!!!");
});


// CHAT COMMANDS


bot.on('message', message => {
    
    if (message.content.startsWith(Prefix + "Post") && message.author.id === "158823576156241921"){
        rbx.post(2960470,"Hello",jar);
    }
});

bot.login(token);
```

**Comment by sentanos** [comment]
Your problem is that you are using jar files incorrectly. If you want to specify one you have to use it for both the login function and the message function `rbx.login('-', '-', jar)`. Because you are using just one user, I recommend removing the jar altogether (and not passing it in) and the module will automatically handle it for you.

**Comment by kinkocat** [comment]
Thank you that was it! Sorry about that, getting used to everything still, Thanks again.
