### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by mwalden2004** [sentanos/roblox-js#70]
Lovely captcha error, Can this be fixed, if so that would be absloutely amazing

**Comment by Neztore** [comment]
@Sloss2003 If you attempt to log into ROBLOX a lot with incorrect details, ROBLOX will add a captcha. This is on ROBLOX's side. Not ours.

If you're not logging in, what action are you attempting?
What is the full error?

**Comment by mwalden2004** [comment]
On the message function, It logins just fine.

**Comment by mwalden2004** [comment]
{error: "captcha"}

**Comment by Neztore** [comment]
@Sloss2003 Can I get the full stack trace

**Comment by Neztore** [comment]
@Sloss2003 Ah. Message function? ROBLOX added a captcha for all users under a certain age. Again, ROBLOX's side not ours. 
We can't do anything about Captchas.

**Comment by mwalden2004** [comment]
No, It's heroku, It is a CAPTCHA ERROR. There is no problem with the code, It's ROBLOX'S captcha, The code needs logic, to bypass it.

**Comment by mwalden2004** [comment]
13+...

**Comment by Neztore** [comment]
ROBLOX added captchas to user endpoints to prevent message botting.

**Comment by Neztore** [comment]
If for some reason you do not believe me, please join [this]( https://discord.gg/EDXNdAT) discord

**Comment by mwalden2004** [comment]
I'm opening an issue, as a suggestion to have something solve it, I know it's possible, It's been done before, it can be done again. This is merely a suggestion, I am experienced, and I do not need to join a discord. I have a ton of programming experience.

**Comment by Neztore** [comment]
@Sloss2003 If you have the ability to bypass a captcha by all means commit your bypass. The main maintainer of this repo does not have enough time.
It's open source. If you want something added, make it.

**Comment by sentanos** [comment]
If OP can find a way or even a person who can bypass captchas for free then by all means let me know.

I’m pretty sure you won’t find them.
