### ISSUE TITLE
getStatus not working properly?

### ISSUE THREAD

**Issue by nishi7409** [sentanos/roblox-js#76]
**Goal:**
To get the status of a user such as when the user runs `!status EliteSilentsword`.

**Problem:**
`const blurb1 = await rbx.getStatus(rbx.getIdFromUsername(args[1]));`

When I run something such as, `!status EliteSilentSword`, it outputs that the user doesn't exist.
Picture - http://prntscr.com/hvshar

When I do something along the lines of...
`const blurb1 = await rbx.getStatus(args[1]);`

And run, `!status 60684854`, it works perfectly fine!

This is an issue because I don't want a user to be finding their userID even though its simple enough to do.  They should just be able to run, `!status username`, and it should pop up.

**Comment by sentanos** [comment]
You are not awaiting the `getIdFromUsername` promise:

```javascript
const blurb = await rbx.getStatus(await rbx.getIdFromUsername(args[1]));
```

**Comment by nishi7409** [comment]
![image](https://user-images.githubusercontent.com/20250366/34548514-8461eac0-f0d0-11e7-9d73-3cba20446c62.png)

I copied your code exactly, yet I get that error.

I ran, `!status EliteSilentSword`.

**Comment by sentanos** [comment]
Works fine for me. Verify args[1] is a string or post code here.

**Comment by nishi7409** [comment]
Ah, I see what the problem was.

a) I was updating the wrong **portion** of the code.
b) What was before triggered what was happening.

Thanks though. 👍
