### ISSUE TITLE
How do I get rank from a member and name them in discord?

### ISSUE THREAD

**Issue by Anonymous0perator** [sentanos/roblox-js#77]
For a example, A is a VIP in the group 4837. So I’m trying to name A like “[VIP] A” like that, I have no idea how to get role and nick that user by rank

**Comment by sentanos** [comment]
To get their role name you would do something like
```javascript
const roleName = await rbx.getRankNameInGroup(groupId, await rbx.getIdFromUsername(username));
```
How to then set their nickname depends on the discord library you are using and is your responsibility to figure out.
