### ISSUE TITLE
How to give role and checking member if they are in group 

### ISSUE THREAD

**Issue by Anonymous0perator** [sentanos/roblox-js#78]
Sentanos, it is your busy day. Sorry about keep requesting and asking, but I really wanted to know about this. 
I have tried coding this thing, it kept sending errors. 
So like if a member do !tagme it will go through all of the group that I have put inside a array, and then giving role. I do not know how to check if member is inside a group. If you are confused, for example. A is inside a group called CAF, if he do !tagme it will check all of the group listed, like CAF, PAF and more. And then if A is in CAF it will giving role called CAF. Sorry again for asking this things.

**Comment by Neztore** [comment]
I cannot understand you
at all.

**Comment by sentanos** [comment]
This is not a well thought out issue for roblox-js
