### ISSUE TITLE
getPlayerInfo returning incorrect age?

### ISSUE THREAD

**Issue by ghost** [sentanos/roblox-js#80]
Apparently, for some users, their age will return incorrectly. For example, my ROBLOX account returns this: https://gyazo.com/bad566277e0ae243590cbbf990e6765d
https://www.roblox.com/users/37854398/profile
This is the code I was running:

```
var rbx = require('roblox-js');
var id = 37854398

console.clear();

rbx.getPlayerInfo({userId: id})
.then(function (Return) {
console.log("That user is " + Return.age + " days old.\n")
}); 
```

How can I fix this?

**Comment by sentanos** [comment]
This is not an official roblox-js function, it shouldn’t be expected to work, and I shouldn’t be responsible for fixing it.

**Comment by Neztore** [comment]
It'll be fixed shortly

**Comment by Neztore** [comment]
@CherryLeaves Fixed, see pull request or [this](https://github.com/Neztore/roblox-js) fork
