### ISSUE TITLE
Unexpected token on line 27

### ISSUE THREAD

**Issue by popeeyy** [sentanos/roblox-js#81]
I'm trying to revert ranks, but when I run this example code you gave, it says "Unexpected token on line 27". How do I fix? Code: https://hastebin.com/ediripiroq.js

**Comment by sentanos** [comment]
You moved around the code... rbx.login is right before the .then

**Comment by popeeyy** [comment]
Now progress isn't a module it says. https://hastebin.com/wujamipeca.js I've reinstalled Roblox.js too.

**Comment by sentanos** [comment]
You have to install all other dependencies such as progress

**Comment by popeeyy** [comment]
What should I execute to install them?

**Comment by sentanos** [comment]
If you don't know how to use node.js and npm please do not try to use these scripts

**Comment by sentanos** [comment]
This issue is unrelated to roblox-js

**Comment by popeeyy** [comment]
I know how to use it, but are you telling me to install it like I did Roblox.js?
