### ISSUE TITLE
Won't Login(Resolved)

### ISSUE THREAD

**Issue by sylv256** [sentanos/roblox-js#90]
Whenever I use the login function along with a setInterval for 500 milliseconds, the terminal will wait for about 1-2 seconds without printing anything then it will stop the script. Does anyone have any idea why this is happening?

Code:
```js
var roblox = require("roblox-js");

var Bot = {
	username: "I put my bot username here",
	password: "I put my bot password here"
};

// Login function(for setInterval)
var login = function() {
        // Log into the account
	roblox.login(Bot.username, Bot.password).then(function() {
                // Notify me it's logged in.
		console.log('Logged in')
	});
};

setInterval(login, 500);
```

**Comment by suufi** [comment]
Why are you logging in every half a second?

**Comment by Neztore** [comment]
^ as well as ROBLOX doesn't like repeated log-ins. They'll captcha you.

You don't need to login twice in single session.
