### ISSUE TITLE
Roblox Captchaed the login page :(

### ISSUE THREAD

**Issue by sylv256** [sentanos/roblox-js#91]
Somone help. I get this error when logging in to a bot.

Unhandled rejection Error: Login failed, known issues: ["Your username or password is incorrect. Please check them and try again."]

I think Roblox Captchaed their API.

**Comment by EraGamer** [comment]
https://github.com/sentanos/roblox-js/issues/82

Read closed requests, they're useful. If it was a captcha error you wouldn't get 

> Your username or password is incorrect. Please check them and try again.

**Comment by sylv256** [comment]
Nevermind, my mistake. I had forgot to wait a day and make sure I had a verified email.
