### ISSUE TITLE
Uh my questions. 

### ISSUE THREAD

**Issue by Anonymous0perator** [sentanos/roblox-js#92]
Okay, hi I have few questions about the getRankNameInGroup.
I'm trying to make my bot like, if you do a command !tagme It will check if username is in group or either have rank in group. If yes It will give a role ghost. I know how to give roles, but I dont know how to make the bot get username in discord and check if member in group or either have rank. thank you

**Comment by suufi** [comment]
Check out discord.js or RoVer by Eva era. There's is no question here.
Please close @sentanos

**Comment by Anonymous0perator** [comment]
nno!!!
