### ISSUE TITLE
[HELP REQUEST] I need to know how to make an onShout Function.

### ISSUE THREAD

**Issue by DamonOnYT** [sentanos/roblox-js#95]
Can anyone like give me an example? Thanks. (Not in wiki)

**Comment by suufi** [comment]
We've added an example to the wiki. 👍

**Comment by lordhammy** [comment]
https://github.com/sentanos/roblox-js/wiki/Usage#events

This page explains how events work, refer to it for onShout or other functions that require events in the future.

**Comment by EirikFA** [comment]
Shouldn't this be closed?

**Comment by DamonOnYT** [comment]
Closed the issue.
