### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by ipadpuppydogdude1** [sentanos/roblox-js#98]
How can I stop the timeout. I looked into the code. And I looked at some closed issues. Some of them are machine related, I am using a cloud 9 vps for testing, and its timing out. is there like a setTimeout function with the time to login? If you do not understand what I am saying, please contact me, and I will give more info.

**Comment by suufi** [comment]
Roblox blocked all incoming requests from C9 iirc. Please don't open up issues if they do not relate directly to the code. Ask on the Discord.

**Comment by ipadpuppydogdude1** [comment]
mk
